---
- hosts: nginx-servers
  sudo: yes
  vars:
   http_port: 8080
  tasks:
  - name: enable EPEL
    yum: name=epel-release

  - name: ensure nginx is installed
    yum: name=nginx state=installed

  - name: ensure the firewall is stopped and disabled at boot time
    service: name=iptables enabled=no state=stopped

  - name: modify the default config to use the given http port
    template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf
    notify: 
    - restart nginx

  - name: customize the default static website
    copy: src={{ item}} dest=/usr/share/nginx/html
    with_items:
     - index.html
     - image.jpg
    notify:
    - restart nginx 

  - name: ensure that nginx runs at boot time.
    service: name=nginx enabled=yes

  handlers:
  - name: restart nginx
    service: name=nginx state=restarted
